# Generated by Django 3.2.5 on 2021-07-20 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keyword',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='keyword', to='blog.keyword'),
            preserve_default=False,
        ),
    ]
