# Generated by Django 3.2.5 on 2021-07-22 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210722_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
